development:
  adapter: postgresql
  database: eurodb_development
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: eurodb_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: eurodb_production
  pool: 5
  timeout: 5000
